# Generated by Django 3.0.3 on 2021-07-18 07:50

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210717_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_linkedin',
            field=models.URLField(blank=True, null=True, validators=[users.models.validate_url_linkedin]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_youtube',
            field=models.URLField(blank=True, null=True, validators=[users.models.validate_url_yt]),
        ),
    ]
